default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: karipic_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: karipic_test

#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>

production:
  <<: *default
  database: karipic_production
  username: karipic
  password: <%= ENV["KARIPIC_DATABASE_PASSWORD"] %>
